# Generated by Django 5.1.1 on 2025-08-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
